CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS dependencies (
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  id VARCHAR PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  id VARCHAR PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_dependencies (
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  id VARCHAR PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  user_id VARCHAR NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  dependency_id VARCHAR NOT NULL REFERENCES dependencies(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sobriety_tracking (
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  id VARCHAR PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  user_id VARCHAR NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  days_per_week INTEGER DEFAULT 0,
  drinks_per_day INTEGER DEFAULT 0,
  motivation_text TEXT
);
